Marille.Tests/WorkQueuesTests.cs, Marille/Hub.cs, Marille/Message.cs, Marille/Topic.cs, Marille/TopicInfo.cs
The tests were not flacky, the code was. We had a few issues because I did not pay attention on how we consume the messages and how we can ensure that we never drop messages:
\# Bugs
1. We were consuming messages withouth workers: dropped messages
2. We were not ensuring that the Create method would return once we started consuming.
To fix the above we had to introduce to changes:
1. If we have no workers, we do not consume messages and let the channel buffer.
2. To be able to coordinate the Consume method and the Create method we added a TaskCompletionSource that will only be set when we have data to consume.
3. If we start with an empty channel, send a Ack message to let the Consume method be ready and the TCS be set.
We have added a struct that wraps the messages default types, this …
=> [Topics] Fix ComsumeChannel coordination. Fixes #3

Marille.Tests/WorkQueuesTests.cs, Marille/Hub.cs, Marille/IWorker.cs, Marille/LambdaWorker.cs, Marille/Message.cs, Marille/Topic.cs, Marille/TopicInfo.cs
It is very tempting to allow users to use structs for the messages, the problem with those is that they will be copying values all over the place, instead, we are going to force users to use reference types.
=> [API] Be more extrict with the type of messages we allow.

Marille.Tests/FastWorker.cs, Marille.Tests/RegistrationTests.cs, Marille.Tests/WorkQueuesTests.cs, Marille/Hub.cs
If the user declares a 1:1 topic we will not allow them to register more than one worker. This will simplify the needed understanding of the execution.
=> [API] Do not allow to create or register more than one worker on 1:1 topics.

Marille.Tests/RegistrationTests.cs, Marille.Tests/WorkQueuesTests.cs, Marille/ChannelDeliveryMode.cs, Marille/Hub.cs
We provide two ways to execute in the 1:1 topics:
- Async: We do will not away for the task and will continue with the next item.
- Sync: We do await for the task that is consuming the current item.
=> [API] Provide two execution modes for the 1:1 channels.

README.md
according to source code, lib will only accept value types for message definitions, not reference types.
=> [docs] fix record --> record struct

Marille.Tests/BlockingWorker.cs, Marille.Tests/CancellationTests.cs, Marille.Tests/WorkQueuesTests.cs, Marille/Hub.cs, Marille/IHub.cs, Marille/Marille.csproj
We add a new API that will allow developers to close a channel or all the channels and wait until all the events to be flushed. This API will always flush messages. We can later add an API that does not flushes the messages by using the cancellation token rather than closing the channel.
=> [API] Add the ability to close channels and wait for all events to be flushed

Marille/Hub.cs, Marille/Topic.cs, Marille/TopicInfo.cs
To make the management of the threads easier, remove the need of an extra dictionary to keep track of the workers. That information can be store in the TopicInfo and we can enforce the casting via generics in a much nicer way.
=> [Internal API] Remove a dictionary by storing workers in the topic info.

Marille/Hub.cs, Marille/Topic.cs, Marille/TopicInfo.cs
The task can be kept in the topic info which simplifies the access and later will allow us to try and remove the dictionary.
=> [Internal API] Remove the need of a tuple to store the consumming task.

Marille/Hub.cs, Marille/Topic.cs, Marille/TopicInfo.cs
Remove the extra data structure and move the cancellation token source to the topic information. This reduces the memory foot print and improvmes the memory management.
=> [Internal API] Remove the need for the cancellation tokens dictionary

Marille.Tests/CancellationTests.cs, Marille.Tests/ErrorHandlingTests.cs, Marille.Tests/ErrorWorker.cs, Marille.Tests/FastWorker.cs, Marille.Tests/PublishSubscribeTests.cs, Marille.Tests/RegistrationTests.cs, Marille.Tests/WorkQueuesTests.cs, Marille/Hub.cs, Marille/IErrorWorker.cs, Marille/IHub.cs, Marille/LambdaErrorWorker.cs, Marille/LambdaWorker.cs, Marille/Marille.csproj, Marille/Message.cs, Marille/Topic.cs, Marille/TopicInfo.cs, README.md
In order to be able to handle errors/exception from workers we are going to provide an API that allows to register an ErrorWorker per topic.
This API allows a worker that is registed to a topic to throw an exception, this exception later will be wrapped in an event passed to the error worker. The event will provide the following data:
1. Message: The message that generated the exception.
2. The exception that was thrown.
Fixes #31
=> [API] Provide an error handling API. Fixes #31

Marille.Tests/CancellationTests.cs, Marille.Tests/PublishSubscribeTests.cs, Marille.Tests/WorkQueuesTests.cs, Marille/ChannelDeliveryMode.cs, Marille/Hub.cs, Marille/TopicConfiguration.cs
This adds a new mode that allow to have several workers in the same topic that will execute in parallel yet we will wait for all of them to complete BEFORE we move fwd.
We also remove capturing lambdas for better memory management.
Fixes #34
=> [API] Execute several workers in parallel but wait before we advance

src/Marille.Tests/CancellationTests.cs, src/Marille.Tests/ErrorHandlingTests.cs, src/Marille.Tests/PublishSubscribeTests.cs, src/Marille.Tests/WorkQueuesTests.cs, src/Marille/Hub.cs, src/Marille/IHub.cs
There are centain cases in which we cannot use async methods, for example on events. The TryPublish method solves that situation allowing to publish an event in the channel with a sync API that will fail if the channel cannot receive more events rather than wait for ever.
=> [API] Proivide a sync API to publish events.

.gitignore, README.md, src/Marille.Tests/CancellationTests.cs, src/Marille.Tests/ErrorHandlingTests.cs, src/Marille.Tests/PublishSubscribeTests.cs, src/Marille.Tests/RegistrationTests.cs, src/Marille.Tests/TopicTests.cs, src/Marille.Tests/WorkQueuesTests.cs, src/Marille.Tests/Workers/BackgroundThreadWorker.cs, src/Marille.Tests/Workers/BlockingWorker.cs, src/Marille.Tests/Workers/ErrorWorker.cs, src/Marille.Tests/Workers/FastWorker.cs, src/Marille.Tests/Workers/SleepyWorker.cs, src/Marille/Hub.cs, src/Marille/IErrorWorker.cs, src/Marille/IWorker.cs, src/Marille/LambdaErrorWorker.cs, src/Marille/LambdaWorker.cs, src/Marille/TopicInfo.cs
Rather than just dealing with IO bound workers we are opening the door to CPU intensive workers.
The new API allows the developer to let the hub know if the worker callback should be executed in a background task or not. This allow users to make the decision to use or no the main thread used by the hub.
There is not need to move the Consuming methods out of the main thread because those are IO bound by definition (readin gfrom a channel is IO bound). The only code that should be executed in a diff thread is that of the consumer.
=> [API] Allow workers to be CPU intensive.

src/Marille.Tests/CancellationTests.cs, src/Marille.Tests/Workers/BackgroundThreadWorker.cs, src/Marille.Tests/Workers/BlockingWorker.cs, src/Marille.Tests/Workers/FastWorker.cs, src/Marille.Tests/Workers/SleepyWorker.cs, src/Marille/Hub.cs, src/Marille/IWorker.cs, src/Marille/LambdaWorker.cs, src/Marille/Marille.csproj, src/Marille/Topic.cs, src/Marille/TopicInfo.cs
It might be the case that the IWorkers are storing state data realted to a topic, therefore we need a way from the IWorkers to know that the channel has been closed and that no more messages are going to be received.
=> [API] Provide a way to notify the IWorkers that a channel has been closed.

src/Marille/Hub.cs, src/Marille/WorkerExtensions.cs
Allow the hub to be able to handle IWorker interface implementations that throw exceptions in the UseBackgroundThread property.
Sometimes it would be nice to have the cocept that java has with the 'throws' keyword :/
=> [Internal API] Protect against properties that throw exceptions.

src/Marille/IWorker.cs
Add a default property implementation for the propery so that users do not have to constantly implement it. This allow developers to ignore the implementation unless thye do want to use a backgrond thread.
=> [API] Default implementation for IWorker.UseBackgroundThread.

.github/workflows/auto_deploy_docs.yml, .github/workflows/deploy.yml
Use the reusable workflow in two actions:
- When we deploy a new nuget version, deploy the docs too.
- When we update any path unders docs, deploy the docs.
=> [Actions] Reuse the deploy docs workflow.

src/Marille.Tests/BaseTimeoutTest.cs, src/Marille.Tests/CancellationTests.cs, src/Marille.Tests/ErrorHandlingTests.cs, src/Marille.Tests/PublishSubscribeTests.cs, src/Marille.Tests/RegistrationTests.cs, src/Marille.Tests/TopicTests.cs, src/Marille.Tests/WorkQueuesTests.cs, src/Marille.Tests/Workers/BlockingWorker.cs, src/Marille/Hub.cs, src/Marille/IHub.cs, src/Marille/Topic.cs
The CloseAsync method had a bug due to a race condition between the way the Dispose pattern could be executing making the tests hang. We have done the following:
1. Fix the issue with the CloseAsync.
2. Change all the tests to have a timeout so that even if we have a bug we do complete the tests.
=> [Bug] Ensure that CloseAsync completes and that the tests do not block.

src/Marille.Tests/ErrorHandlingTests.cs, src/Marille.Tests/MessageTests.cs, src/Marille.Tests/TopicConfigurationTests.cs, src/Marille/Hub.cs, src/Marille/Message.cs, src/Marille/Topic.cs, src/Marille/TopicConfiguration.cs
Allow channels to resend and event if it has to be retried. The message will be queued again since it is a "new Event".
=> [API] Implement the error retry logic.

src/Marille.Tests/ErrorHandlingTests.cs, src/Marille.Tests/PublishSubscribeTests.cs, src/Marille.Tests/TopicConfigurationTests.cs, src/Marille/ConsumeTaskData.cs, src/Marille/Hub.cs, src/Marille/Topic.cs, src/Marille/TopicConfiguration.cs, src/Marille/TopicInfo.cs, src/global.json
Allow users not to exceed the maximum parallelism when creating a new hub by allow to set a max parallel option. When the option is set, rather than DOS attacking the thread pool of dotnet, the hub will use a semaphore to throttle the number of threads used.
=> [API] Implement max parallel
